### ISSUE TITLE
Missing Plugin Exception 

### ISSUE THREAD

**Issue by AniketBynaric** [easebuzz/paywitheasebuzz-flutter-lib#5]
This exception is occured for me. 
I have tried pug clean & pub get, but issue still occurs. I have followed all the necessary steps given.
I'm using Kotlin for native. 

```
E/flutter (17237): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method payWithEasebuzz on channel easebuzz)
E/flutter (17237): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:313:7)
E/flutter (17237): <asynchronous suspension>
E/flutter (17237): #1      _MyHomePageState._incrementCounter (package:easebuzz_demo/main.dart:65:30)
E/flutter (17237): <asynchronous suspension>
```

**Comment by tanishq14developer** [comment]
Did you able to resolve this Issue @AniketBynaric ?

**Comment by sur2548** [comment]
Configure the method channel inside `configureFlutterEngine` method.

Example

```
override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)

        start_payment = true

        MethodChannel(
            flutterEngine.dartExecutor.binaryMessenger,
            CHANNEL
        ).setMethodCallHandler { call, result ->
            Log.e("com.meadow.kart", call.method)
            channel_result = result
            if (call.method == "payWithEasebuzz") {
                if (start_payment) {
                    start_payment = false
                    startPayment(call.arguments)
                }
            }
        }
    }
```

**Comment by tanishq14developer** [comment]
@sur2548  Thanks for the help it worked. 
Can you in docs where it is mentioned ?

**Comment by sur2548** [comment]
> @sur2548 Thanks for the help it worked. Can you in docs where it is mentioned ?

I do not think it is there in the doc.
